### ISSUE TITLE
Welcome Page: All Careers and Majors

### ISSUE THREAD

**Issue by Brian-Miki** [BobaTalks/pick-a-major#15]
## Description
This should cover just the two lists below, both the careers and the majors lists. No need for the quiz CTA on the right to be included in this work

## Acceptance Criteria
- Lists [stack](https://mui.com/material-ui/react-stack/) vertically while in mobile view
- Items should link to their respective pages i.e. `/majors/biology-health?what` or something that makes sense

![image](https://user-images.githubusercontent.com/115371047/223626100-670265ca-78d1-45b5-b9db-bdd3dac7eed4.png)
(On quiz result and welcome pages)

**Comment by Raymond0T** [comment]
In-progress
