### ISSUE TITLE
Quiz Results

### ISSUE THREAD

**Issue by Brian-Miki** [BobaTalks/pick-a-major#20]
![image](https://user-images.githubusercontent.com/115371047/223626969-0789c26b-2461-4a0a-822e-938500e8f952.png)

- [ ] Title (Careers and majors) and description (Explore majors, careers and more)
- [ ] Subtitle (Quiz Results)
- [ ] Major Card
- [ ] Stack of Major Cards
- [ ] All Careers and Majors Text (Links too)
- [ ] Boba Bot
- [ ] Major Guide (Title) and Explore Majors and careers (Subtitle)
- [ ] Scroll Down Button
- [ ] Background Design

**Comment by Raymond0T** [comment]
In-progress
