### ISSUE TITLE
Specific Major Info

### ISSUE THREAD

**Issue by Brian-Miki** [BobaTalks/pick-a-major#21]
![image](https://user-images.githubusercontent.com/115371047/223627072-2310252a-92ed-4c3f-acc1-fe4984598433.png)

- [ ] Title
- [ ] Breadcrumb
- [ ] Tabs + Box
- [ ] Content
- [ ] Scroll Up Button
- [ ] Background Design

**Comment by jshiii117** [comment]
Pls add me as an assignee!
