### ISSUE TITLE
Logic: Data in JSON file

### ISSUE THREAD

**Issue by Brian-Miki** [BobaTalks/pick-a-major#24]
https://docs.google.com/document/d/1f4qoz3ay-KBVMPGkFFIQkuSjQu7XADqWj7BC6GzTeXA/edit?usp=sharing
To be put into JSON file(s)?

**Comment by Raymond0T** [comment]
In-progress

**Comment by jwu910** [comment]
@Raymond0T i saw your PR also had this. you should be able to create a new branch and pull these files out as well on to a new branch and put that up for review
