### ISSUE TITLE
Nav Bar: Navigation Bar

### ISSUE THREAD

**Issue by Brian-Miki** [BobaTalks/pick-a-major#25]
![Image](https://user-images.githubusercontent.com/118410579/230690129-a667bb72-5bd6-4e13-930c-5062b68452f5.png)

**Comment by jwu910** [comment]
@Brian-Miki do we know what this will look like yet?

**Comment by Brian-Miki** [comment]
New nav bar can be found in "Specs for developers" currently. Will update design about getting this onto Hi-fi soon too.

**Comment by kpxwinter** [comment]
Update: Design has been updated, current screenshot is hi-fi version
