### ISSUE TITLE
Results: Subtitle (Quiz Results)

### ISSUE THREAD

**Issue by jshiii117** [BobaTalks/pick-a-major#57]
![Image](https://user-images.githubusercontent.com/118410579/230690663-87f6b32f-46ed-4d84-8696-c1e1fb2fc518.png)

This text specifically:

![Image](https://user-images.githubusercontent.com/118410579/230690698-ec4aea70-dfb8-4433-81bc-04a4efb1f1fd.png)

**Comment by jwu910** [comment]
@Brian-Miki next time it would be more helpful to have a wider screenshot to have more context on this. and/or a link to the node on figma

**Comment by Raymond0T** [comment]
In-progress

**Comment by kpxwinter** [comment]
Update: wider screenshot updated based on hi-fi design
