### ISSUE TITLE
Results: All Careers and Majors Text (Links too)

### ISSUE THREAD

**Issue by jshiii117** [BobaTalks/pick-a-major#60]
## Description

~Blocked by #15~

![image](https://user-images.githubusercontent.com/74488095/226075823-a406f68d-acea-41af-98f4-409ad4670961.png)

**Comment by jwu910** [comment]
What does "Links too" mean? If this component is being created by @Raymond0T, this will be just adding the component to the results page right?

**Comment by Brian-Miki** [comment]
Link too the respective major/career page



![Image](https://user-images.githubusercontent.com/115371047/233863463-6b0ac08d-c720-48ab-9fad-6271b41a2d54.png)
