### ISSUE TITLE
Create Page components and routes for each step in the app

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/pick-a-major#73]
## Description
Make sure we have routes for each view
/home
/quiz?step={1|2|3}
/results
/receipt
/majors

## To discuss
The `/quiz` route will have multiple ways to achieve this. We can have separate routes for each step, or you can use query params as saveable state for the user

**Comment by jshiii117** [comment]
I will do this!!1

**Comment by jwu910** [comment]
@jshiii117 where are we with this?

Btw, to link PRs, we can use the keyword phrase `Fixes #123` in the pull request description if one is open
